// GENERATED by scripts/sync-deepseek-prices.ts — do not edit by hand.
// Source: https://api-docs.deepseek.com/zh-cn/quick_start/pricing/
// Fetched at: 2026-08-14T14:27:49.568Z

/** One model's per-1M-token prices, in CNY (元). */
export interface DeepSeekPriceEntry {
  readonly inputCacheHitYuanPerM: number
  readonly inputCacheMissYuanPerM: number
  readonly outputYuanPerM: number
}

/** Official DeepSeek price table, synced at build time. */
export interface DeepSeekPrices {
  readonly sourceUrl: string
  /** ISO instant of the last successful sync. */
  readonly fetchedAt: string
  /** Beijing-time peak windows ([startHour, endHour), hour in Beijing time). */
  readonly peakHours: readonly { readonly start: number; readonly end: number }[]
  /** Epoch ms of the Beijing-time instant peak/off-peak pricing takes effect. */
  readonly effectiveFromMs: number
  /** Prices before `effectiveFromMs` (Beijing time). */
  readonly base: Readonly<Record<string, DeepSeekPriceEntry>>
  /** Off-peak prices from `effectiveFromMs`. */
  readonly offPeak: Readonly<Record<string, DeepSeekPriceEntry>>
  /** Peak prices from `effectiveFromMs` during `peakHours`. */
  readonly peak: Readonly<Record<string, DeepSeekPriceEntry>>
}

export const DEEPSEEK_PRICES: DeepSeekPrices = {
  sourceUrl: 'https://api-docs.deepseek.com/zh-cn/quick_start/pricing/',
  fetchedAt: '2026-08-14T14:27:49.568Z',
  peakHours: [{ start: 9, end: 12 }, { start: 14, end: 18 }],
  effectiveFromMs: 1786896000000,
  base: {
    'deepseek-v4-flash': { inputCacheHitYuanPerM: 0.02, inputCacheMissYuanPerM: 1, outputYuanPerM: 2 },
    'deepseek-v4-pro': { inputCacheHitYuanPerM: 0.025, inputCacheMissYuanPerM: 3, outputYuanPerM: 6 },
  },
  offPeak: {
    'deepseek-v4-flash': { inputCacheHitYuanPerM: 0.05, inputCacheMissYuanPerM: 1.5, outputYuanPerM: 4.5 },
    'deepseek-v4-pro': { inputCacheHitYuanPerM: 0.15, inputCacheMissYuanPerM: 4.5, outputYuanPerM: 13.5 },
  },
  peak: {
    'deepseek-v4-flash': { inputCacheHitYuanPerM: 0.1, inputCacheMissYuanPerM: 3, outputYuanPerM: 9 },
    'deepseek-v4-pro': { inputCacheHitYuanPerM: 0.3, inputCacheMissYuanPerM: 9, outputYuanPerM: 27 },
  },
}
